FROM cannin/jupyter-keras-tensorflow-tools:tf-1.15.2-py3

# Installing required software
#RUN apt-get update
#


RUN apt-get install -y openssh-server
RUN apt-get install -y supervisor
RUN apt-get install -y sudo

RUN adduser testku
RUN echo 'testku:testku' | chpasswd

RUN echo 'root:root' | chpasswd

#RUN adduser test
#RUN echo 'Testtest!' | passwd --stdin test
#RUN echo 'test:test' | chpasswd

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

RUN mkdir /var/run/sshd

#RUN service ssh start
# Enabling root login
RUN sed -i 's/#PermitRootLogin.*/PermitRootLogin\ yes/g' /etc/ssh/sshd_config 
#RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

#CMD ["/usr/sbin/sshd","-D"]
#CMD service ssh start && while true; do sleep 3000; done



ENV NOTVISIBLE "in users profile"
RUN echo "export PYTHONPATH=$PYTHONPATH:/root/models/research:/root/models/research/object_detection:/root/models/research/slim:/root/models/research/slim/datasets:/root/models/research/slim/deployment:/root/models/research/slim/nets:/root/models/researh/slim/preprocessing:/root/models/research/slim/scripts" >> /etc/profile
RUN echo "export VISIBLE=now" >> /etc/profile

COPY supervisor/*.conf /etc/supervisor/conf.d/



ENTRYPOINT ["sh", "/docker-entrypoint.sh"]



EXPOSE 22
EXPOSE 8000
EXPOSE 5000


#WORKDIR /notebooks
WORKDIR "/root/models/research/object_detection"

CMD ["/usr/bin/supervisord"]
